// <auto-generated />
using System;
using ClinicApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicApi.Migrations
{
    [DbContext(typeof(DentalClinicContext))]
    partial class DentalClinicContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicApi.Models.Entities.Appointment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("appointment_start_time")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<int>("duration_minutes")
                        .HasColumnType("integer");

                    b.Property<string>("notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("patient_id")
                        .HasColumnType("uuid");

                    b.Property<string>("reason_for_visit")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("staff_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("status_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("patient_id");

                    b.HasIndex("staff_id");

                    b.HasIndex("status_id");

                    b.ToTable("appointment");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.AppointmentStatus", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("appointment_status", (string)null);
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Billing", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("amount_paid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<DateTime>("due_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("issue_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("patient_id")
                        .HasColumnType("uuid");

                    b.Property<string>("status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Draft");

                    b.Property<decimal>("total_amount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("patient_id");

                    b.ToTable("billing");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.BillingLineItem", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("billing_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("discount_percentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<int>("quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid?>("treatment_id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("unit_price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("billing_id");

                    b.HasIndex("treatment_id");

                    b.ToTable("billing_line_item", (string)null);
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.DiscountType", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<string>("discount_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("discount_percentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("discount_type", (string)null);
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Document", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("document_path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("document_type_id")
                        .HasColumnType("uuid");

                    b.Property<bool>("is_sensitive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("patient_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("tooth_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("treatment_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("upload_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("document_type_id");

                    b.HasIndex("patient_id");

                    b.HasIndex("tooth_id");

                    b.HasIndex("treatment_id");

                    b.ToTable("document");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.DocumentType", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("document_type_code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("document_type");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.ToTable("document_type", (string)null);
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Patient", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<string>("emergency_contact_name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("emergency_contact_phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("person_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("person_id")
                        .IsUnique();

                    b.ToTable("patient");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Payment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("billing_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("method")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("payment_date")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("transaction_ref")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("id");

                    b.HasIndex("billing_id");

                    b.ToTable("payment");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Person", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("a_identifier")
                        .HasColumnType("text");

                    b.Property<string>("address")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<DateTime?>("date_of_birth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("gender")
                        .HasColumnType("text");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("phone_number")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("person");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Prescription", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<string>("dosage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("drug_name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("instructions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("treatment_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("treatment_id");

                    b.ToTable("prescription");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Role", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id");

                    b.ToTable("role");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.SaleItem", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<Guid?>("discount_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("patient_id")
                        .HasColumnType("uuid");

                    b.Property<int>("quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("discount_id");

                    b.HasIndex("patient_id");

                    b.ToTable("sale_item", (string)null);
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Service", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("specialty_id")
                        .HasColumnType("uuid");

                    b.HasKey("id");

                    b.HasIndex("specialty_id");

                    b.ToTable("service");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Specialty", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("id");

                    b.ToTable("specialty");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Staff", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<bool>("is_active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("license_number")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("person_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("role_id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("specialty_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("person_id")
                        .IsUnique();

                    b.HasIndex("role_id");

                    b.HasIndex("specialty_id");

                    b.ToTable("staff");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Tooth", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("patient_id")
                        .HasColumnType("uuid");

                    b.Property<string>("tooth_name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("tooth_number")
                        .HasColumnType("integer");

                    b.Property<Guid>("tooth_status_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("tooth_status_id");

                    b.HasIndex("patient_id", "tooth_number")
                        .IsUnique();

                    b.ToTable("tooth");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.ToothStatus", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("id");

                    b.HasIndex("code")
                        .IsUnique();

                    b.ToTable("tooth_status", (string)null);
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Treatment", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("appointment_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("created_by")
                        .HasColumnType("text");

                    b.Property<string>("notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("patient_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("service_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("staff_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("tooth_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("updated_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("updated_by")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("appointment_id");

                    b.HasIndex("patient_id");

                    b.HasIndex("service_id");

                    b.HasIndex("staff_id");

                    b.HasIndex("tooth_id");

                    b.ToTable("treatment");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Appointment", b =>
                {
                    b.HasOne("ClinicApi.Models.Entities.Patient", "patient")
                        .WithMany("appointments")
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicApi.Models.Entities.Staff", "staff")
                        .WithMany("appointments")
                        .HasForeignKey("staff_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicApi.Models.Entities.AppointmentStatus", "status")
                        .WithMany("appointments")
                        .HasForeignKey("status_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("patient");

                    b.Navigation("staff");

                    b.Navigation("status");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Billing", b =>
                {
                    b.HasOne("ClinicApi.Models.Entities.Patient", "patient")
                        .WithMany("billings")
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("patient");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.BillingLineItem", b =>
                {
                    b.HasOne("ClinicApi.Models.Entities.Billing", "billing")
                        .WithMany("billing_line_Item")
                        .HasForeignKey("billing_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicApi.Models.Entities.Treatment", "treatment")
                        .WithMany("billing_line_item")
                        .HasForeignKey("treatment_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("billing");

                    b.Navigation("treatment");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Document", b =>
                {
                    b.HasOne("ClinicApi.Models.Entities.DocumentType", "document_type")
                        .WithMany("documents")
                        .HasForeignKey("document_type_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicApi.Models.Entities.Patient", "patient")
                        .WithMany("documents")
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicApi.Models.Entities.Tooth", "tooth")
                        .WithMany("documents")
                        .HasForeignKey("tooth_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClinicApi.Models.Entities.Treatment", "treatment")
                        .WithMany("documents")
                        .HasForeignKey("treatment_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("document_type");

                    b.Navigation("patient");

                    b.Navigation("tooth");

                    b.Navigation("treatment");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Patient", b =>
                {
                    b.HasOne("ClinicApi.Models.Entities.Person", "Person")
                        .WithOne()
                        .HasForeignKey("ClinicApi.Models.Entities.Patient", "person_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Payment", b =>
                {
                    b.HasOne("ClinicApi.Models.Entities.Billing", "billing")
                        .WithMany("payment")
                        .HasForeignKey("billing_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("billing");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Prescription", b =>
                {
                    b.HasOne("ClinicApi.Models.Entities.Treatment", "treatment")
                        .WithMany("prescriptions")
                        .HasForeignKey("treatment_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("treatment");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.SaleItem", b =>
                {
                    b.HasOne("ClinicApi.Models.Entities.DiscountType", "discount_type")
                        .WithMany("sale_item")
                        .HasForeignKey("discount_id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ClinicApi.Models.Entities.Patient", "patient")
                        .WithMany("sale_items")
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("discount_type");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Service", b =>
                {
                    b.HasOne("ClinicApi.Models.Entities.Specialty", "specialty")
                        .WithMany("services")
                        .HasForeignKey("specialty_id");

                    b.Navigation("specialty");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Staff", b =>
                {
                    b.HasOne("ClinicApi.Models.Entities.Person", "person")
                        .WithOne()
                        .HasForeignKey("ClinicApi.Models.Entities.Staff", "person_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicApi.Models.Entities.Role", "role")
                        .WithMany("staff")
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicApi.Models.Entities.Specialty", "specialty")
                        .WithMany("staff")
                        .HasForeignKey("specialty_id");

                    b.Navigation("person");

                    b.Navigation("role");

                    b.Navigation("specialty");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Tooth", b =>
                {
                    b.HasOne("ClinicApi.Models.Entities.Patient", "patient")
                        .WithMany("teeth")
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicApi.Models.Entities.ToothStatus", "tooth_status")
                        .WithMany("teeth")
                        .HasForeignKey("tooth_status_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("patient");

                    b.Navigation("tooth_status");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Treatment", b =>
                {
                    b.HasOne("ClinicApi.Models.Entities.Appointment", "appointment")
                        .WithMany("treatments")
                        .HasForeignKey("appointment_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicApi.Models.Entities.Patient", "patient")
                        .WithMany("treatments")
                        .HasForeignKey("patient_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicApi.Models.Entities.Service", "service")
                        .WithMany("treatments")
                        .HasForeignKey("service_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicApi.Models.Entities.Staff", "staff")
                        .WithMany("treatments")
                        .HasForeignKey("staff_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ClinicApi.Models.Entities.Tooth", "tooth")
                        .WithMany("treatments")
                        .HasForeignKey("tooth_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("appointment");

                    b.Navigation("patient");

                    b.Navigation("service");

                    b.Navigation("staff");

                    b.Navigation("tooth");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Appointment", b =>
                {
                    b.Navigation("treatments");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.AppointmentStatus", b =>
                {
                    b.Navigation("appointments");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Billing", b =>
                {
                    b.Navigation("billing_line_Item");

                    b.Navigation("payment");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.DiscountType", b =>
                {
                    b.Navigation("sale_item");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.DocumentType", b =>
                {
                    b.Navigation("documents");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Patient", b =>
                {
                    b.Navigation("appointments");

                    b.Navigation("billings");

                    b.Navigation("documents");

                    b.Navigation("sale_items");

                    b.Navigation("teeth");

                    b.Navigation("treatments");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Role", b =>
                {
                    b.Navigation("staff");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Service", b =>
                {
                    b.Navigation("treatments");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Specialty", b =>
                {
                    b.Navigation("services");

                    b.Navigation("staff");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Staff", b =>
                {
                    b.Navigation("appointments");

                    b.Navigation("treatments");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Tooth", b =>
                {
                    b.Navigation("documents");

                    b.Navigation("treatments");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.ToothStatus", b =>
                {
                    b.Navigation("teeth");
                });

            modelBuilder.Entity("ClinicApi.Models.Entities.Treatment", b =>
                {
                    b.Navigation("billing_line_item");

                    b.Navigation("documents");

                    b.Navigation("prescriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
